import { validateApplicationToken, getPropertyById } from '@/lib/api';
import ApplicationForm from '@/components/ApplicationForm';
import { Card, CardContent } from '@/components/ui/card';

export default async function ApplyPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  // The [id] in the URL can be either:
  // 1. An application link token (generated by manager) - needs to be validated first
  // 2. A direct property ID (for testing or direct access)
  const tokenOrPropertyId = id;

  try {
    let propertyId: string;
    let applicationToken: string | undefined;

    // First, try to validate as an application link token
    const validation = await validateApplicationToken(tokenOrPropertyId);
    
    if (validation.valid && validation.propertyId) {
      // It's a valid application link token
      propertyId = validation.propertyId;
      applicationToken = tokenOrPropertyId;
    } else {
      // Fallback: treat it as a direct property ID (for testing)
      propertyId = tokenOrPropertyId;
    }

    // Fetch the property details
    const property = await getPropertyById(propertyId);

    return (
      <div className="container py-10">
        <ApplicationForm property={property} token={applicationToken} />
      </div>
    );
  } catch (error) {
    console.error('Error loading property:', error);
    return (
      <div className="container flex items-center justify-center min-h-screen">
          <Card className="w-full max-w-md">
              <CardContent className="pt-6 text-center">
                  <h2 className="text-xl font-bold text-red-600 mb-2">Error Loading Property</h2>
                  <p className="text-muted-foreground">
                      We couldn't find the property you're looking for. The link might be expired or invalid.
                  </p>
              </CardContent>
          </Card>
      </div>
    );
  }
}
