'use client'

import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import {
  TerminalPanel,
  StatusBadge,
  PropertyTypeBadge,
  AlertBanner,
  MethodBadge,
  StepIndicator,
  ConfidenceBar,
} from '@/components/ui/terminal'
import { valuationsApi, marketDataApi } from '@/lib/valuation-api'
import type { Valuation, ValuationMethod, MarketConditions } from '@/types/valuation'
import {
  ArrowLeft,
  ArrowRight,
  Loader2,
  CheckCircle2,
  Info,
  TrendingUp,
  DollarSign,
  Building,
  Calculator,
  BarChart3,
  Percent,
} from 'lucide-react'

// Valuation method definitions
interface MethodDefinition {
  id: ValuationMethod
  name: string
  shortName: string
  description: string
  icon: React.ReactNode
  applicability: {
    residential: number
    commercial: number
    industrial: number
    land: number
    mixed_use: number
    specialized: number
  }
  dataRequirements: string[]
  advantages: string[]
  limitations: string[]
}

const VALUATION_METHODS: MethodDefinition[] = [
  {
    id: 'sales_comparison',
    name: 'Sales Comparison Approach',
    shortName: 'SALES COMP',
    description: 'Compares the subject property to similar properties that have recently sold, with adjustments for differences.',
    icon: <TrendingUp className="w-5 h-5" />,
    applicability: {
      residential: 95,
      commercial: 70,
      industrial: 60,
      land: 90,
      mixed_use: 65,
      specialized: 30,
    },
    dataRequirements: [
      'Recent comparable sales',
      'Property characteristics',
      'Market conditions data',
      'Location quality metrics',
    ],
    advantages: [
      'Most direct reflection of market value',
      'Easy to understand',
      'Based on actual transactions',
    ],
    limitations: [
      'Requires sufficient comparable sales',
      'Adjustments can be subjective',
      'Less reliable in inactive markets',
    ],
  },
  {
    id: 'cost_approach',
    name: 'Cost Approach',
    shortName: 'COST',
    description: 'Estimates value based on the cost to reproduce or replace the improvements, less depreciation, plus land value.',
    icon: <Building className="w-5 h-5" />,
    applicability: {
      residential: 60,
      commercial: 65,
      industrial: 80,
      land: 20,
      mixed_use: 55,
      specialized: 90,
    },
    dataRequirements: [
      'Construction cost data',
      'Land value estimate',
      'Depreciation analysis',
      'Building specifications',
    ],
    advantages: [
      'Works for unique properties',
      'Upper limit indicator',
      'Good for new construction',
    ],
    limitations: [
      'Depreciation estimation is subjective',
      'May not reflect market behavior',
      'Less reliable for older buildings',
    ],
  },
  {
    id: 'income_approach',
    name: 'Income Approach',
    shortName: 'INCOME',
    description: 'Values property based on its income-generating potential using capitalization or DCF analysis.',
    icon: <DollarSign className="w-5 h-5" />,
    applicability: {
      residential: 40,
      commercial: 95,
      industrial: 85,
      land: 30,
      mixed_use: 80,
      specialized: 70,
    },
    dataRequirements: [
      'Rental income data',
      'Operating expenses',
      'Capitalization rates',
      'Vacancy rates',
    ],
    advantages: [
      'Reflects investor perspective',
      'Based on income potential',
      'Good for investment properties',
    ],
    limitations: [
      'Requires income data',
      'Cap rate selection subjective',
      'Not suitable for owner-occupied',
    ],
  },
  {
    id: 'residual_method',
    name: 'Residual Method',
    shortName: 'RESIDUAL',
    description: 'Determines land value by deducting development costs and profit from the completed development value.',
    icon: <Calculator className="w-5 h-5" />,
    applicability: {
      residential: 50,
      commercial: 60,
      industrial: 55,
      land: 95,
      mixed_use: 70,
      specialized: 45,
    },
    dataRequirements: [
      'Development plans',
      'Construction costs',
      'Developer profit margins',
      'End value estimates',
    ],
    advantages: [
      'Best for development sites',
      'Accounts for development potential',
      'Reflects developer logic',
    ],
    limitations: [
      'Many assumptions required',
      'Sensitive to inputs',
      'Requires development expertise',
    ],
  },
  {
    id: 'profits_method',
    name: 'Profits Method',
    shortName: 'PROFITS',
    description: 'Values property based on the trading potential and profits generated by the business conducted on it.',
    icon: <BarChart3 className="w-5 h-5" />,
    applicability: {
      residential: 10,
      commercial: 50,
      industrial: 40,
      land: 10,
      mixed_use: 35,
      specialized: 85,
    },
    dataRequirements: [
      'Business accounts',
      'Trading history',
      'Market rent equivalents',
      'Industry benchmarks',
    ],
    advantages: [
      'Suitable for trade-related properties',
      'Reflects business value',
      'Industry-specific approach',
    ],
    limitations: [
      'Limited to specific property types',
      'Requires financial analysis',
      'Business performance dependent',
    ],
  },
  {
    id: 'drc_method',
    name: 'Depreciated Replacement Cost',
    shortName: 'DRC',
    description: 'Values specialized properties with no market evidence using replacement cost less depreciation.',
    icon: <Percent className="w-5 h-5" />,
    applicability: {
      residential: 20,
      commercial: 30,
      industrial: 65,
      land: 10,
      mixed_use: 25,
      specialized: 95,
    },
    dataRequirements: [
      'Replacement cost estimates',
      'Depreciation schedules',
      'Functional obsolescence',
      'Economic obsolescence',
    ],
    advantages: [
      'Works for unique properties',
      'Last resort valuation',
      'Systematic approach',
    ],
    limitations: [
      'Not market-based',
      'Depreciation estimates subjective',
      'May not reflect exchange value',
    ],
  },
]

export default function MethodSelectionPage() {
  const params = useParams()
  const router = useRouter()
  const valuationId = params.id as string

  const [valuation, setValuation] = useState<Valuation | null>(null)
  const [marketData, setMarketData] = useState<MarketConditions | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Method selection state
  const [selectedMethods, setSelectedMethods] = useState<ValuationMethod[]>([])
  const [primaryMethod, setPrimaryMethod] = useState<ValuationMethod | null>(null)
  const [methodWeights, setMethodWeights] = useState<Record<ValuationMethod, number>>({
    sales_comparison: 0,
    cost_approach: 0,
    income_approach: 0,
    residual_method: 0,
    profits_method: 0,
    drc_method: 0,
  })
  const [activeMethodDetail, setActiveMethodDetail] = useState<ValuationMethod | null>(null)
  const [selectionNotes, setSelectionNotes] = useState('')

  // Fetch valuation and market data
  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true)
        setError(null)

        const valuationRes = await valuationsApi.getById(valuationId)
        if (valuationRes.error) throw new Error(valuationRes.error)
        if (!valuationRes.data) throw new Error('Valuation not found')

        setValuation(valuationRes.data as Valuation)

        // Pre-select methods if already set
        if (valuationRes.data.selectedMethods) {
          setSelectedMethods(valuationRes.data.selectedMethods)
        }
        if (valuationRes.data.primary_method) {
          setPrimaryMethod(valuationRes.data.primary_method as ValuationMethod)
        }
        if (valuationRes.data.methodWeights) {
          setMethodWeights({ ...methodWeights, ...valuationRes.data.methodWeights })
        }

        // Fetch market data for recommendations
        const property = valuationRes.data.property
        if (property) {
          const marketRes = await marketDataApi.getConditions(
            property.region || 'greater_accra',
            property.propertyType
          )
          if (marketRes.data) {
            setMarketData(marketRes.data)
          }
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load valuation')
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [valuationId])

  // Get property type for applicability
  const propertyType = (valuation?.property?.property_type || 'residential') as keyof MethodDefinition['applicability']

  // Toggle method selection
  const toggleMethod = (methodId: ValuationMethod) => {
    if (selectedMethods.includes(methodId)) {
      setSelectedMethods(selectedMethods.filter(m => m !== methodId))
      if (primaryMethod === methodId) {
        setPrimaryMethod(selectedMethods.find(m => m !== methodId) || null)
      }
      setMethodWeights({ ...methodWeights, [methodId]: 0 })
    } else {
      setSelectedMethods([...selectedMethods, methodId])
      // Auto-distribute weights
      const newMethods = [...selectedMethods, methodId]
      const weight = Math.floor(100 / newMethods.length)
      const newWeights = { ...methodWeights }
      newMethods.forEach(m => {
        newWeights[m] = weight
      })
      setMethodWeights(newWeights)
      
      if (!primaryMethod) {
        setPrimaryMethod(methodId)
      }
    }
  }

  // Set primary method
  const handleSetPrimary = (methodId: ValuationMethod) => {
    if (selectedMethods.includes(methodId)) {
      setPrimaryMethod(methodId)
    }
  }

  // Update weight
  const updateWeight = (methodId: ValuationMethod, weight: number) => {
    setMethodWeights({ ...methodWeights, [methodId]: weight })
  }

  // Calculate total weight
  const totalWeight = Object.entries(methodWeights)
    .filter(([m]) => selectedMethods.includes(m as ValuationMethod))
    .reduce((sum, [, w]) => sum + w, 0)

  // Get recommended methods based on property type
  const recommendedMethods = VALUATION_METHODS
    .filter(m => m.applicability[propertyType] >= 60)
    .map(m => m.id)

  // Save and continue
  const handleSaveAndContinue = async () => {
    try {
      setSaving(true)
      setError(null)

      if (selectedMethods.length === 0) {
        throw new Error('Please select at least one valuation method')
      }

      if (!primaryMethod) {
        throw new Error('Please select a primary method')
      }

      if (Math.abs(totalWeight - 100) > 1) {
        throw new Error('Method weights must sum to 100%')
      }

      // Update valuation with method selection
      // Use snake_case field names to match backend API expectations
      const updateResult = await valuationsApi.update(valuationId, {
        methods_applied: selectedMethods,
        primary_method: primaryMethod,
        method_weights: methodWeights,
        current_step: 5, // Advance past methods to first method step
      })

      // Check if update failed
      if (updateResult.error) {
        throw new Error(updateResult.error)
      }

      // Determine next step based on selected methods
      // Sales Comparison requires comparables, so always go to comparables first
      // Income Approach benefits from rental comparables, so go to rental-market first
      // Other methods can benefit from comparables but don't require them
      const hasSalesComparison = selectedMethods.includes('sales_comparison')
      const hasIncomeApproach = selectedMethods.includes('income_approach')
      
      if (hasSalesComparison) {
        // Sales Comparison needs comparables - go to Comparables page
        router.push(`/dashboard/valuations/${valuationId}/comparables`)
      } else {
        // No Sales Comparison - route based on selected methods
        // If income approach is selected, go to rental-market first
        const methodRoutes: Record<string, string> = {
          'cost_approach': 'cost',
          'income_approach': 'rental-market', // Route to rental market first, then income
          'drc_method': 'drc',
          'profits_method': 'profits',
          'residual_method': 'residual',
        }
        
        // Find first selected method in workflow order
        const workflowOrder = ['cost_approach', 'income_approach', 'drc_method', 'profits_method', 'residual_method']
        const firstMethod = workflowOrder.find(m => selectedMethods.includes(m as ValuationMethod))
        
        if (firstMethod && methodRoutes[firstMethod]) {
          router.push(`/dashboard/valuations/${valuationId}/${methodRoutes[firstMethod]}`)
        } else {
          // Fallback to reconciliation if no matching route
          router.push(`/dashboard/valuations/${valuationId}/reconciliation`)
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save method selection')
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-amber-500 animate-spin" />
        <span className="ml-3 font-mono text-sm text-muted-foreground">Loading method selection...</span>
      </div>
    )
  }

  if (error || !valuation) {
    return (
      <div className="min-h-screen bg-background text-foreground p-4">
        <AlertBanner type="error" title="Error" message={error || 'Valuation not found'} />
      </div>
    )
  }

  const property = valuation.property
  const activeMethod = activeMethodDetail ? VALUATION_METHODS.find(m => m.id === activeMethodDetail) : null

  return (
    <div className="min-h-screen bg-background text-foreground p-4 pb-10">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <Link
            href={`/dashboard/valuations/${valuationId}`}
            className="p-2 hover:bg-muted transition-colors"
          >
            <ArrowLeft className="w-4 h-4 text-muted-foreground" />
          </Link>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="font-mono text-xl text-foreground">STEP 3: METHOD SELECTION</h1>
              <StatusBadge status="in_progress" />
            </div>
            <p className="font-mono text-[10px] text-muted-foreground">
              Select Valuation Approaches • VAL-{valuationId.slice(0, 8).toUpperCase()}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleSaveAndContinue}
            disabled={saving || selectedMethods.length === 0}
            className="flex items-center gap-2 px-4 py-2 bg-amber-500 text-foreground font-mono text-xs font-bold hover:bg-amber-400 transition-colors disabled:opacity-50"
          >
            {saving ? (
              <>
                <Loader2 className="w-3 h-3 animate-spin" />
                SAVING...
              </>
            ) : (
              <>
                SAVE & CONTINUE
                <ArrowRight className="w-3 h-3" />
              </>
            )}
          </button>
        </div>
      </div>

      {/* Step Progress */}
      <div className="mb-6">
        <StepIndicator
          steps={[
            { id: 1, label: 'Property Setup', status: 'completed' },
            { id: 2, label: 'Floor Plans', status: 'completed' },
            { id: 3, label: 'HBU Analysis', status: 'completed' },
            { id: 4, label: 'Method Selection', status: 'current' },
            { id: 5, label: 'Valuation', status: 'upcoming' },
            { id: 6, label: 'Reconciliation', status: 'upcoming' },
            { id: 7, label: 'Report', status: 'upcoming' },
          ]}
        />
      </div>

      {/* Recommendation Banner */}
      <div className="mb-6 p-4 bg-amber-100 dark:bg-amber-900/20 border border-amber-500/30 flex items-start gap-3">
        <Info className="w-5 h-5 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
        <div>
          <div className="font-mono text-sm text-amber-600 dark:text-amber-400">Recommended for {propertyType.toUpperCase()}</div>
          <div className="font-mono text-xs text-muted-foreground mt-1">
            Based on property type and market conditions, we recommend: {' '}
            {recommendedMethods.map((m, i) => (
              <span key={m}>
                <span className="text-amber-600 dark:text-amber-400">
                  {VALUATION_METHODS.find(method => method.id === m)?.shortName}
                </span>
                {i < recommendedMethods.length - 1 ? ', ' : ''}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && <AlertBanner type="error" title="Error" message={error} />}

      {/* Method Selection Grid */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {VALUATION_METHODS.map((method) => {
          const isSelected = selectedMethods.includes(method.id)
          const isPrimary = primaryMethod === method.id
          const applicability = method.applicability[propertyType]
          const isRecommended = applicability >= 60

          return (
            <div
              key={method.id}
              className={`border transition-colors ${
                isSelected 
                  ? isPrimary 
                    ? 'border-amber-500 bg-amber-500/10' 
                    : 'border-green-500/50 bg-green-500/5'
                  : 'border-border hover:border-border'
              }`}
            >
              <div className="p-4">
                <div className="flex items-start justify-between mb-3">
                  <div className={isSelected ? (isPrimary ? 'text-amber-600 dark:text-amber-400' : 'text-green-600 dark:text-green-400') : 'text-muted-foreground'}>
                    {method.icon}
                  </div>
                  <div className="flex items-center gap-2">
                    {isRecommended && (
                      <span className="font-mono text-[9px] px-1.5 py-0.5 bg-amber-500/20 text-amber-600 dark:text-amber-400">
                        REC
                      </span>
                    )}
                    {isPrimary && (
                      <span className="font-mono text-[9px] px-1.5 py-0.5 bg-amber-500 text-foreground font-bold">
                        PRIMARY
                      </span>
                    )}
                  </div>
                </div>

                <div className="font-mono text-sm text-foreground mb-1">{method.name}</div>
                <div className="font-mono text-[10px] text-muted-foreground mb-3 line-clamp-2">{method.description}</div>

                <div className="mb-3">
                  <div className="flex justify-between items-center mb-1">
                    <span className="font-mono text-[9px] text-muted-foreground">APPLICABILITY</span>
                    <span className="font-mono text-[9px] text-muted-foreground">{applicability}%</span>
                  </div>
                  <ConfidenceBar score={applicability} showValue={false} />
                </div>

                <div className="flex gap-2">
                  <button
                    onClick={() => toggleMethod(method.id)}
                    className={`flex-1 py-2 font-mono text-xs transition-colors ${
                      isSelected
                        ? 'bg-zinc-700 text-foreground'
                        : 'bg-muted text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    {isSelected ? 'SELECTED ✓' : 'SELECT'}
                  </button>
                  <button
                    onClick={() => setActiveMethodDetail(method.id)}
                    className="px-3 py-2 bg-muted text-muted-foreground font-mono text-xs hover:text-foreground transition-colors"
                  >
                    INFO
                  </button>
                </div>

                {isSelected && (
                  <div className="mt-3 pt-3 border-t border-border">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-[10px] text-muted-foreground">WEIGHT:</span>
                        <input
                          type="number"
                          min="0"
                          max="100"
                          value={methodWeights[method.id]}
                          onChange={(e) => updateWeight(method.id, parseInt(e.target.value) || 0)}
                          className="w-14 px-2 py-1 bg-muted border border-border text-foreground font-mono text-xs text-center focus:outline-none focus:border-amber-500/50"
                        />
                        <span className="font-mono text-[10px] text-muted-foreground">%</span>
                      </div>
                      {!isPrimary && (
                        <button
                          onClick={() => handleSetPrimary(method.id)}
                          className="font-mono text-[10px] text-amber-600 dark:text-amber-400 hover:text-amber-300"
                        >
                          SET PRIMARY
                        </button>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {/* Weight Summary */}
      {selectedMethods.length > 0 && (
        <TerminalPanel title="METHOD WEIGHTS" className="mb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              {selectedMethods.map((methodId) => {
                const method = VALUATION_METHODS.find(m => m.id === methodId)
                return (
                  <div key={methodId} className="flex items-center gap-2">
                    <MethodBadge method={methodId} isPrimary={methodId === primaryMethod} />
                    <span className="font-mono text-xs text-muted-foreground">{methodWeights[methodId]}%</span>
                  </div>
                )
              })}
            </div>
            <div className={`font-mono text-sm ${
              Math.abs(totalWeight - 100) <= 1 ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'
            }`}>
              TOTAL: {totalWeight}%
              {Math.abs(totalWeight - 100) > 1 && (
                <span className="text-red-600 dark:text-red-400 ml-2">⚠ Must equal 100%</span>
              )}
            </div>
          </div>
        </TerminalPanel>
      )}

      {/* Method Detail Modal */}
      {activeMethod && (
        <div className="fixed inset-0 bg-background/80 z-50 flex items-center justify-center p-4">
          <div className="bg-card border border-border max-w-2xl w-full max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b border-border">
              <div className="flex items-center gap-3">
                <div className="text-amber-600 dark:text-amber-400">{activeMethod.icon}</div>
                <div className="font-mono text-lg text-foreground">{activeMethod.name}</div>
              </div>
              <button
                onClick={() => setActiveMethodDetail(null)}
                className="font-mono text-xs text-muted-foreground hover:text-foreground"
              >
                CLOSE ✕
              </button>
            </div>
            <div className="p-4 space-y-4">
              <div>
                <div className="font-mono text-[10px] text-muted-foreground mb-1">DESCRIPTION</div>
                <div className="font-mono text-sm text-muted-foreground">{activeMethod.description}</div>
              </div>

              <div>
                <div className="font-mono text-[10px] text-muted-foreground mb-2">DATA REQUIREMENTS</div>
                <ul className="space-y-1">
                  {activeMethod.dataRequirements.map((req, i) => (
                    <li key={i} className="flex items-center gap-2 font-mono text-xs text-muted-foreground">
                      <span className="w-1 h-1 bg-amber-500 rounded-full" />
                      {req}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="font-mono text-[10px] text-green-500 mb-2">ADVANTAGES</div>
                  <ul className="space-y-1">
                    {activeMethod.advantages.map((adv, i) => (
                      <li key={i} className="flex items-center gap-2 font-mono text-xs text-muted-foreground">
                        <CheckCircle2 className="w-3 h-3 text-green-600 dark:text-green-400 flex-shrink-0" />
                        {adv}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <div className="font-mono text-[10px] text-red-500 mb-2">LIMITATIONS</div>
                  <ul className="space-y-1">
                    {activeMethod.limitations.map((lim, i) => (
                      <li key={i} className="flex items-center gap-2 font-mono text-xs text-muted-foreground">
                        <span className="w-1 h-1 bg-red-500 rounded-full flex-shrink-0" />
                        {lim}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div>
                <div className="font-mono text-[10px] text-muted-foreground mb-2">APPLICABILITY BY PROPERTY TYPE</div>
                <div className="grid grid-cols-3 gap-2">
                  {Object.entries(activeMethod.applicability).map(([type, score]) => (
                    <div key={type} className="p-2 bg-muted/50 border border-border">
                      <div className="font-mono text-[10px] text-muted-foreground mb-1">{type.toUpperCase()}</div>
                      <ConfidenceBar score={score} />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Selection Notes */}
      <TerminalPanel title="METHOD SELECTION RATIONALE" className="mt-4">
        <textarea
          value={selectionNotes}
          onChange={(e) => setSelectionNotes(e.target.value)}
          placeholder="Document your reasoning for selecting these valuation methods..."
          rows={3}
          className="w-full px-3 py-2 bg-card border border-border text-foreground font-mono text-sm placeholder-zinc-600 focus:outline-none focus:border-amber-500/50 resize-none"
        />
      </TerminalPanel>

      {/* Navigation */}
      <div className="mt-6 flex justify-between">
        <Link
          href={`/dashboard/valuations/${valuationId}/hbu`}
          className="px-6 py-3 bg-muted text-muted-foreground font-mono text-sm hover:text-foreground transition-colors"
        >
          ← BACK TO HBU ANALYSIS
        </Link>
        <button
          onClick={handleSaveAndContinue}
          disabled={saving || selectedMethods.length === 0}
          className="flex items-center gap-2 px-6 py-3 bg-amber-500 text-foreground font-mono text-sm font-bold hover:bg-amber-400 transition-colors disabled:opacity-50"
        >
          {saving ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              SAVING...
            </>
          ) : (
            <>
              CONTINUE TO VALUATION
              <ArrowRight className="w-4 h-4" />
            </>
          )}
        </button>
      </div>
    </div>
  )
}
