/**
 * Deal Service
 * Phase 5.2: CRM Service Layer
 * 
 * Handles deal lifecycle management with pipeline validation
 */

import { v4 as uuidv4 } from 'uuid';
import db from '../../database';
import { logger } from '../../utils/logger';
import {
    Deal,
    CreateDealInput,
    UpdateDealInput,
    DealFilters,
    PaginatedResponse,
} from './types';
import { pipelineValidator } from './pipelineValidator';
import { activityService } from './activityService';

export class DealService {
    /**
     * Create a new deal
     */
    async createDeal(
        organizationId: string,
        data: CreateDealInput,
        userId?: string
    ): Promise<Deal> {
        const client = await db.getClient();

        try {
            await client.query('BEGIN');

            const id = uuidv4();

            // Validate pipeline and stage
            await pipelineValidator.validateStageInPipeline(
                data.pipeline_id,
                data.stage_id,
                organizationId
            );

            // Create deal (deal_number is auto-generated by trigger)
            const result = await client.query<Deal>(
                `INSERT INTO deals (
          id, organization_id, title, description,
          primary_contact_id, secondary_contacts, property_ids, company_id,
          assigned_agent, assigned_team, deal_owners,
          deal_type, pipeline_id, stage_id, deal_status,
          deal_value, currency, commission_amount, commission_percentage,
          estimated_close_date, close_probability,
          lead_source, campaign_source, utm_data,
          tags, notes, custom_fields, created_by, first_contact_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
          $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, NOW()
        ) RETURNING *`,
                [
                    id,
                    organizationId,
                    data.title,
                    data.description || null,
                    data.primary_contact_id,
                    data.secondary_contacts || null,
                    data.property_ids || null,
                    data.company_id || null,
                    data.assigned_agent, // Required - must be a valid agent ID
                    data.assigned_team || null,
                    userId ? [userId] : null, // Deal creator is first owner
                    data.deal_type,
                    data.pipeline_id,
                    data.stage_id,
                    'active',
                    data.deal_value || null,
                    'GHS',
                    data.deal_value && data.deal_value > 0
                        ? data.deal_value * 0.05
                        : null, // Default 5% commission
                    data.deal_value && data.deal_value > 0 ? 5.0 : null,
                    data.estimated_close_date || null,
                    data.close_probability || 50,
                    data.lead_source || null,
                    data.campaign_source || null,
                    null, // utm_data
                    data.tags || null,
                    data.notes || null,
                    null, // custom_fields
                    userId || null,
                ]
            );

            const deal = result.rows[0];

            // Create initial activity log
            await activityService.createActivity(
                {
                    deal_id: id,
                    user_id: userId || data.assigned_agent,
                    activity_type: 'stage_change',
                    subject: 'Deal created',
                    description: `Deal "${data.title}" created`,
                    outcome: 'completed',
                    new_value: { stage_id: data.stage_id, status: 'active' },
                },
                client
            );

            await client.query('COMMIT');

            logger.info('Deal created', { dealId: id, organizationId, dealNumber: deal.deal_number });

            // Track contribution for Data Hub
            try {
                const { ServiceHooks } = await import('../data-hub/serviceHooks');
                await ServiceHooks.createContribution({
                    contributor_id: userId || null,
                    organization_id: organizationId,
                    contribution_type: 'crm_deal',
                    source_context: 'crm',
                    source_id: id,
                    data: {
                        deal_id: id,
                        deal_number: deal.deal_number,
                        title: data.title,
                        deal_value: data.deal_value,
                        deal_type: data.deal_type,
                        action: 'deal_creation',
                    },
                });
            } catch (hookError) {
                logger.error('Failed to create deal contribution hook', hookError);
            }

            return deal;
        } catch (error) {
            await client.query('ROLLBACK');
            logger.error('Error creating deal', { error, organizationId });
            throw error;
        } finally {
            client.release();
        }
    }

    /**
     * Get deal by ID with full relations
     */
    async getDealById(dealId: string, organizationId: string): Promise<Deal | null> {
        try {
            const result = await db.query<Deal>(
                `SELECT 
          d.*,
          c.first_name || ' ' || c.last_name as primary_contact_name,
          c.primary_phone as primary_contact_phone,
          c.email as primary_contact_email,
          comp.company_name,
          dp.pipeline_name,
          ds.stage_name,
          ds.stage_color,
          ag.first_name || ' ' || ag.last_name as assigned_agent_name,
          ag.email as assigned_agent_email,
          ag.phone_primary as assigned_agent_phone
         FROM deals d
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         LEFT JOIN companies comp ON d.company_id = comp.id
         LEFT JOIN deal_pipelines dp ON d.pipeline_id = dp.id
         LEFT JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN agents ag ON d.assigned_agent = ag.id
         WHERE d.id = $1 AND d.organization_id = $2 AND d.deleted_at IS NULL`,
                [dealId, organizationId]
            );

            return result.rows[0] || null;
        } catch (error) {
            logger.error('Error fetching deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * List deals with filters and pagination
     */
    async listDeals(
        organizationId: string,
        filters: DealFilters = {}
    ): Promise<PaginatedResponse<Deal>> {
        try {
            const page = filters.page || 1;
            const limit = filters.limit || 50;
            const offset = (page - 1) * limit;

            const conditions: string[] = ['d.organization_id = $1', 'd.deleted_at IS NULL'];
            const params: any[] = [organizationId];
            let paramIndex = 2;

            if (filters.search) {
                conditions.push(`(d.title ILIKE $${paramIndex} OR d.deal_number ILIKE $${paramIndex + 1})`);
                params.push(`%${filters.search}%`, `%${filters.search}%`);
                paramIndex += 2;
            }

            if (filters.deal_type) {
                conditions.push(`d.deal_type = $${paramIndex}`);
                params.push(filters.deal_type);
                paramIndex++;
            }

            if (filters.deal_status) {
                conditions.push(`d.deal_status = $${paramIndex}`);
                params.push(filters.deal_status);
                paramIndex++;
            }

            if (filters.pipeline_id) {
                conditions.push(`d.pipeline_id = $${paramIndex}`);
                params.push(filters.pipeline_id);
                paramIndex++;
            }

            if (filters.stage_id) {
                conditions.push(`d.stage_id = $${paramIndex}`);
                params.push(filters.stage_id);
                paramIndex++;
            }

            if (filters.assigned_agent) {
                conditions.push(`d.assigned_agent = $${paramIndex}`);
                params.push(filters.assigned_agent);
                paramIndex++;
            }

            if (filters.deal_value_min !== undefined) {
                conditions.push(`d.deal_value >= $${paramIndex}`);
                params.push(filters.deal_value_min);
                paramIndex++;
            }

            if (filters.deal_value_max !== undefined) {
                conditions.push(`d.deal_value <= $${paramIndex}`);
                params.push(filters.deal_value_max);
                paramIndex++;
            }

            if (filters.tags && filters.tags.length > 0) {
                conditions.push(`d.tags && $${paramIndex}`);
                params.push(filters.tags);
                paramIndex++;
            }

            const whereClause = conditions.join(' AND ');
            const sortBy = filters.sort_by || 'created_at';
            const sortOrder = filters.sort_order || 'desc';
            const orderBy = `d.${sortBy} ${sortOrder.toUpperCase()}`;

            // Get total count
            const countResult = await db.query(
                `SELECT COUNT(*) as total FROM deals d WHERE ${whereClause}`,
                params
            );
            const total = parseInt(countResult.rows[0].total, 10);

            // Get paginated data
            const dataParams = [...params, limit, offset];
            const result = await db.query<Deal>(
                `SELECT 
          d.*,
          c.first_name || ' ' || c.last_name as primary_contact_name,
          ds.stage_name,
          ds.stage_color,
          dp.pipeline_name
         FROM deals d
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         LEFT JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN deal_pipelines dp ON d.pipeline_id = dp.id
         WHERE ${whereClause}
         ORDER BY ${orderBy}
         LIMIT $${paramIndex} OFFSET $${paramIndex + 1}`,
                dataParams
            );

            return {
                data: result.rows,
                pagination: {
                    total,
                    page,
                    limit,
                    total_pages: Math.ceil(total / limit),
                },
            };
        } catch (error) {
            logger.error('Error listing deals', { error, organizationId });
            throw error;
        }
    }

    /**
     * Update deal (includes pipeline/stage changes)
     */
    async updateDeal(
        dealId: string,
        organizationId: string,
        data: UpdateDealInput,
        userId?: string
    ): Promise<Deal> {
        try {
            const updates: string[] = [];
            const params: any[] = [];
            let paramIndex = 1;

            const fields: (keyof UpdateDealInput)[] = [
                'title',
                'description',
                'secondary_contacts',
                'property_ids',
                'assigned_agent',
                'deal_value',
                'estimated_close_date',
                'close_probability',
                'tags',
                'notes',
                'custom_fields',
                'pipeline_id',
                'stage_id',
                'primary_contact_id',
                'company_id',
                'deal_type',
                'deal_status',
                'expected_close_date',
                'probability',
                'commission_rate',
                'commission_amount',
                'lead_source',
            ];

            for (const field of fields) {
                if (data[field] !== undefined) {
                    updates.push(`${field} = $${paramIndex}`);
                    params.push(
                        field === 'custom_fields' ? JSON.stringify(data[field]) : data[field]
                    );
                    paramIndex++;
                }
            }

            if (userId) {
                updates.push(`updated_by = $${paramIndex}`);
                params.push(userId);
                paramIndex++;
            }

            if (updates.length === 0) {
                throw new Error('No fields to update');
            }

            params.push(dealId, organizationId);

            const result = await db.query<Deal>(
                `UPDATE deals
         SET ${updates.join(', ')}
         WHERE id = $${paramIndex} AND organization_id = $${paramIndex + 1} AND deleted_at IS NULL
         RETURNING *`,
                params
            );

            if (result.rows.length === 0) {
                throw new Error('Deal not found or unauthorized');
            }

            logger.info('Deal updated', { dealId, organizationId });
            return result.rows[0];
        } catch (error) {
            logger.error('Error updating deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * Update deal stage with validation
     */
    async updateDealStage(
        dealId: string,
        newStageId: string,
        organizationId: string,
        userId?: string,
        notes?: string
    ): Promise<Deal> {
        const client = await db.getClient();

        try {
            await client.query('BEGIN');

            // Get current deal
            const dealResult = await client.query<Deal>(
                `SELECT * FROM deals WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`,
                [dealId, organizationId]
            );

            if (dealResult.rows.length === 0) {
                throw new Error('Deal not found');
            }

            const deal = dealResult.rows[0];
            const oldStageId = deal.stage_id;

            // Validate stage transition
            await pipelineValidator.validateStageTransition(
                deal.pipeline_id,
                oldStageId,
                newStageId,
                organizationId
            );

            // Update deal stage
            const updateResult = await client.query<Deal>(
                `UPDATE deals
         SET stage_id = $1, stage_changed_at = NOW(), updated_at = NOW(), updated_by = $2
         WHERE id = $3 AND organization_id = $4
         RETURNING *`,
                [newStageId, userId || null, dealId, organizationId]
            );

            const updatedDeal = updateResult.rows[0];

            // Log stage change activity
            await activityService.createActivity(
                {
                    deal_id: dealId,
                    user_id: userId || deal.assigned_agent,
                    activity_type: 'stage_change',
                    subject: 'Deal stage changed',
                    description: notes || 'Deal moved to new stage',
                    outcome: 'completed',
                    old_value: { stage_id: oldStageId },
                    new_value: { stage_id: newStageId },
                },
                client
            );

            await client.query('COMMIT');

            logger.info('Deal stage updated', {
                dealId,
                organizationId,
                oldStageId,
                newStageId,
            });

            return updatedDeal;
        } catch (error) {
            await client.query('ROLLBACK');
            logger.error('Error updating deal stage', { error, dealId, organizationId });
            throw error;
        } finally {
            client.release();
        }
    }

    /**
     * Soft delete deal
     */
    async deleteDeal(dealId: string, organizationId: string): Promise<void> {
        try {
            const result = await db.query(
                `UPDATE deals
         SET deleted_at = NOW(), deal_status = 'archived'
         WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
         RETURNING id`,
                [dealId, organizationId]
            );

            if (result.rows.length === 0) {
                throw new Error('Deal not found or already deleted');
            }

            logger.info('Deal soft deleted', { dealId, organizationId });
        } catch (error) {
            logger.error('Error deleting deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * Get deals by pipeline stage (for Kanban board)
     */
    async getDealsByStage(
        organizationId: string,
        pipelineId: string
    ): Promise<Record<string, Deal[]>> {
        try {
            const result = await db.query<Deal & { stage_name: string; stage_order: number }>(
                `SELECT 
          d.*,
          ds.stage_name,
          ds.stage_order,
          ds.stage_color,
          c.first_name || ' ' || c.last_name as primary_contact_name
         FROM deals d
         JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         WHERE d.organization_id = $1 
           AND d.pipeline_id = $2 
           AND d.deleted_at IS NULL
           AND d.deal_status = 'active'
         ORDER BY ds.stage_order, d.created_at DESC`,
                [organizationId, pipelineId]
            );

            // Group by stage
            const dealsByStage: Record<string, Deal[]> = {};
            for (const deal of result.rows) {
                const stageId = deal.stage_id;
                if (!dealsByStage[stageId]) {
                    dealsByStage[stageId] = [];
                }
                dealsByStage[stageId].push(deal);
            }

            return dealsByStage;
        } catch (error) {
            logger.error('Error fetching deals by stage', { error, organizationId, pipelineId });
            throw error;
        }
    }

    /**
     * Get deal metrics
     */
    async getDealMetrics(organizationId: string): Promise<{
        total_active: number;
        total_value: number;
        total_weighted_value: number;
        won_deals: number;
        lost_deals: number;
        avg_close_probability: number;
        by_stage: Record<string, { count: number; total_value: number }>;
    }> {
        try {
            const result = await db.query(
                `SELECT 
          COUNT(*) FILTER (WHERE deal_status = 'active') as total_active,
          COUNT(*) FILTER (WHERE deal_status = 'won') as won_deals,
          COUNT(*) FILTER (WHERE deal_status = 'lost') as lost_deals,
          COALESCE(SUM(deal_value) FILTER (WHERE deal_status = 'active'), 0) as total_value,
          COALESCE(SUM(weighted_value) FILTER (WHERE deal_status = 'active'), 0) as total_weighted_value,
          AVG(close_probability) FILTER (WHERE deal_status = 'active') as avg_close_probability
         FROM deals
         WHERE organization_id = $1 AND deleted_at IS NULL`,
                [organizationId]
            );

            const metrics = result.rows[0];

            // Get by stage
            const stageResult = await db.query(
                `SELECT 
          ds.stage_name,
          COUNT(d.id) as count,
          COALESCE(SUM(d.deal_value), 0) as total_value
         FROM deal_stages ds
         LEFT JOIN deals d ON ds.id = d.stage_id AND d.deal_status = 'active' AND d.deleted_at IS NULL
         JOIN deal_pipelines dp ON ds.pipeline_id = dp.id
         WHERE dp.organization_id = $1
         GROUP BY ds.stage_name`,
                [organizationId]
            );

            const byStage: Record<string, { count: number; total_value: number }> = {};
            for (const row of stageResult.rows) {
                byStage[row.stage_name] = {
                    count: parseInt(row.count, 10),
                    total_value: parseFloat(row.total_value),
                };
            }

            return {
                total_active: parseInt(metrics.total_active, 10),
                total_value: parseFloat(metrics.total_value),
                total_weighted_value: parseFloat(metrics.total_weighted_value),
                won_deals: parseInt(metrics.won_deals, 10),
                lost_deals: parseInt(metrics.lost_deals, 10),
                avg_close_probability: parseFloat(metrics.avg_close_probability) || 50,
                by_stage: byStage,
            };
        } catch (error) {
            logger.error('Error fetching deal metrics', { error, organizationId });
            throw error;
        }
    }
}

export const dealService = new DealService();
