/**
 * Deal Service
 * Phase 5.2: CRM Service Layer
 * Phase 4 E-Sign Integration: Automatic contract signing on stage transitions
 * 
 * Handles deal lifecycle management with pipeline validation
 */

import { v4 as uuidv4 } from 'uuid';
import db from '../../database';
import { logger } from '../../utils/logger';
import {
    Deal,
    CreateDealInput,
    UpdateDealInput,
    DealFilters,
    PaginatedResponse,
} from './types';
import { pipelineValidator } from './pipelineValidator';
import { activityService } from './activityService';
import { eSignIntegrationService } from '../../../shared-services/e-sign/integration/eSignIntegrationService';
import { CompletionEvent, ESignField } from '../../../shared-services/e-sign/integration/types';
import { calendarService } from '../../../shared-services/calendar/calendarService';

export class DealService {
    /**
     * Create a new deal
     */
    async createDeal(
        organizationId: string,
        data: CreateDealInput,
        userId?: string
    ): Promise<Deal> {
        const client = await db.getClient();

        try {
            await client.query('BEGIN');

            const id = uuidv4();

            // Validate pipeline and stage
            await pipelineValidator.validateStageInPipeline(
                data.pipeline_id,
                data.stage_id,
                organizationId
            );

            // Create deal (deal_number is auto-generated by trigger)
            const result = await client.query<Deal>(
                `INSERT INTO deals (
          id, organization_id, title, description,
          primary_contact_id, secondary_contacts, property_ids, company_id,
          assigned_agent, assigned_team, deal_owners,
          deal_type, pipeline_id, stage_id, deal_status,
          deal_value, currency, commission_amount, commission_percentage,
          estimated_close_date, close_probability,
          lead_source, campaign_source, utm_data,
          tags, notes, custom_fields, created_by, first_contact_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
          $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, NOW()
        ) RETURNING *`,
                [
                    id,
                    organizationId,
                    data.title,
                    data.description || null,
                    data.primary_contact_id,
                    data.secondary_contacts || null,
                    data.property_ids || null,
                    data.company_id || null,
                    data.assigned_agent, // Required - must be a valid agent ID
                    data.assigned_team || null,
                    userId ? [userId] : null, // Deal creator is first owner
                    data.deal_type,
                    data.pipeline_id,
                    data.stage_id,
                    'active',
                    data.deal_value || null,
                    'GHS',
                    data.deal_value && data.deal_value > 0
                        ? data.deal_value * 0.05
                        : null, // Default 5% commission
                    data.deal_value && data.deal_value > 0 ? 5.0 : null,
                    data.estimated_close_date || null,
                    data.close_probability || 50,
                    data.lead_source || null,
                    data.campaign_source || null,
                    null, // utm_data
                    data.tags || null,
                    data.notes || null,
                    null, // custom_fields
                    userId || null,
                ]
            );

            const deal = result.rows[0];

            // Create initial activity log (savepoint protects against legacy trigger cascade)
            try {
                await client.query('SAVEPOINT activity_log');
                await activityService.createActivity(
                    {
                        deal_id: id,
                        user_id: userId || data.assigned_agent,
                        activity_type: 'stage_change',
                        subject: 'Deal created',
                        description: `Deal "${data.title}" created`,
                        outcome: 'completed',
                        new_value: { stage_id: data.stage_id, status: 'active' },
                    },
                    client
                );
                await client.query('RELEASE SAVEPOINT activity_log');
            } catch (activityError: any) {
                await client.query('ROLLBACK TO SAVEPOINT activity_log');
                logger.warn('Failed to create initial activity for deal (legacy trigger)', {
                    dealId: id,
                    error: activityError.message,
                });
            }

            await client.query('COMMIT');

            logger.info('Deal created', { dealId: id, organizationId, dealNumber: deal.deal_number });

            // Track contribution for Data Hub
            try {
                const { ServiceHooks } = await import('../data-hub/serviceHooks');
                await ServiceHooks.createContribution({
                    contributor_id: userId || null,
                    organization_id: organizationId,
                    contribution_type: 'crm_deal',
                    source_context: 'crm',
                    source_id: id,
                    data: {
                        deal_id: id,
                        deal_number: deal.deal_number,
                        title: data.title,
                        deal_value: data.deal_value,
                        deal_type: data.deal_type,
                        action: 'deal_creation',
                    },
                });
            } catch (hookError) {
                logger.error('Failed to create deal contribution hook', hookError);
            }

            return deal;
        } catch (error) {
            await client.query('ROLLBACK');
            logger.error('Error creating deal', { error, organizationId });
            throw error;
        } finally {
            client.release();
        }
    }

    /**
     * Get deal by ID with full relations
     */
    async getDealById(dealId: string, organizationId: string): Promise<Deal | null> {
        try {
            const result = await db.query<Deal>(
                `SELECT 
          d.*,
          c.first_name || ' ' || c.last_name as primary_contact_name,
          c.primary_phone as primary_contact_phone,
          c.email as primary_contact_email,
          comp.company_name,
          dp.pipeline_name,
          ds.stage_name,
          ds.stage_color,
          ag.first_name || ' ' || ag.last_name as assigned_agent_name,
          ag.email as assigned_agent_email,
          ag.phone_primary as assigned_agent_phone,
          (SELECT ARRAY_AGG(title) FROM crm_properties WHERE id = ANY(d.property_ids)) as property_names,
          (SELECT EXISTS(SELECT 1 FROM valuations v WHERE v.property_id = ANY(d.property_ids) AND v.status = 'completed')) as has_valuation
         FROM deals d
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         LEFT JOIN companies comp ON d.company_id = comp.id
         LEFT JOIN deal_pipelines dp ON d.pipeline_id = dp.id
         LEFT JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN agents ag ON d.assigned_agent = ag.id
         WHERE d.id = $1 AND d.organization_id = $2 AND d.deleted_at IS NULL`,
                [dealId, organizationId]
            );

            return result.rows[0] || null;
        } catch (error) {
            logger.error('Error fetching deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * List deals with filters and pagination
     */
    async listDeals(
        organizationId: string,
        filters: DealFilters = {}
    ): Promise<PaginatedResponse<Deal>> {
        try {
            const page = filters.page || 1;
            const limit = filters.limit || 50;
            const offset = (page - 1) * limit;

            const conditions: string[] = ['d.organization_id = $1', 'd.deleted_at IS NULL'];
            const params: any[] = [organizationId];
            let paramIndex = 2;

            if (filters.search) {
                conditions.push(`(d.title ILIKE $${paramIndex} OR d.deal_number ILIKE $${paramIndex + 1})`);
                params.push(`%${filters.search}%`, `%${filters.search}%`);
                paramIndex += 2;
            }

            if (filters.deal_type) {
                conditions.push(`d.deal_type = $${paramIndex}`);
                params.push(filters.deal_type);
                paramIndex++;
            }

            if (filters.deal_status) {
                conditions.push(`d.deal_status = $${paramIndex}`);
                params.push(filters.deal_status);
                paramIndex++;
            }

            if (filters.pipeline_id) {
                conditions.push(`d.pipeline_id = $${paramIndex}`);
                params.push(filters.pipeline_id);
                paramIndex++;
            }

            if (filters.stage_id) {
                conditions.push(`d.stage_id = $${paramIndex}`);
                params.push(filters.stage_id);
                paramIndex++;
            }

            if (filters.assigned_agent) {
                conditions.push(`d.assigned_agent = $${paramIndex}`);
                params.push(filters.assigned_agent);
                paramIndex++;
            }

            if (filters.deal_value_min !== undefined) {
                conditions.push(`d.deal_value >= $${paramIndex}`);
                params.push(filters.deal_value_min);
                paramIndex++;
            }

            if (filters.deal_value_max !== undefined) {
                conditions.push(`d.deal_value <= $${paramIndex}`);
                params.push(filters.deal_value_max);
                paramIndex++;
            }

            if (filters.tags && filters.tags.length > 0) {
                conditions.push(`d.tags && $${paramIndex}`);
                params.push(filters.tags);
                paramIndex++;
            }

            const whereClause = conditions.join(' AND ');
            const sortBy = filters.sort_by || 'created_at';
            const sortOrder = filters.sort_order || 'desc';
            const orderBy = `d.${sortBy} ${sortOrder.toUpperCase()}`;

            // Get total count
            const countResult = await db.query(
                `SELECT COUNT(*) as total FROM deals d WHERE ${whereClause}`,
                params
            );
            const total = parseInt(countResult.rows[0].total, 10);

            // Get paginated data
            const dataParams = [...params, limit, offset];
            const result = await db.query<Deal>(
                `SELECT 
          d.*,
          c.first_name || ' ' || c.last_name as primary_contact_name,
          ds.stage_name,
          ds.stage_color,
          dp.pipeline_name,
          (SELECT ARRAY_AGG(title) FROM crm_properties WHERE id = ANY(d.property_ids)) as property_names,
          (SELECT EXISTS(SELECT 1 FROM valuations v WHERE v.property_id = ANY(d.property_ids) AND v.status = 'completed')) as has_valuation
         FROM deals d
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         LEFT JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN deal_pipelines dp ON d.pipeline_id = dp.id
         WHERE ${whereClause}
         ORDER BY ${orderBy}
         LIMIT $${paramIndex} OFFSET $${paramIndex + 1}`,
                dataParams
            );

            return {
                data: result.rows,
                pagination: {
                    total,
                    page,
                    limit,
                    total_pages: Math.ceil(total / limit),
                },
            };
        } catch (error) {
            logger.error('Error listing deals', { error, organizationId });
            throw error;
        }
    }

    /**
     * Update deal (includes pipeline/stage changes)
     */
    async updateDeal(
        dealId: string,
        organizationId: string,
        data: UpdateDealInput,
        userId?: string
    ): Promise<Deal> {
        try {
            const updates: string[] = [];
            const params: any[] = [];
            let paramIndex = 1;

            const fields: (keyof UpdateDealInput)[] = [
                'title',
                'description',
                'secondary_contacts',
                'property_ids',
                'assigned_agent',
                'deal_value',
                'estimated_close_date',
                'close_probability',
                'tags',
                'notes',
                'custom_fields',
                'pipeline_id',
                'stage_id',
                'primary_contact_id',
                'company_id',
                'deal_type',
                'deal_status',
                'expected_close_date',
                'probability',
                'commission_rate',
                'commission_amount',
                'lead_source',
            ];

            // Map frontend field names to actual DB column names
            const fieldToColumn: Record<string, string> = {
                probability: 'close_probability',
            };

            for (const field of fields) {
                if (data[field] !== undefined) {
                    const column = fieldToColumn[field] || field;
                    updates.push(`${column} = $${paramIndex}`);
                    params.push(
                        field === 'custom_fields' ? JSON.stringify(data[field]) : data[field]
                    );
                    paramIndex++;
                }
            }

            if (userId) {
                updates.push(`updated_by = $${paramIndex}`);
                params.push(userId);
                paramIndex++;
            }

            if (updates.length === 0) {
                throw new Error('No fields to update');
            }

            params.push(dealId, organizationId);

            const result = await db.query<Deal>(
                `UPDATE deals
         SET ${updates.join(', ')}
         WHERE id = $${paramIndex} AND organization_id = $${paramIndex + 1} AND deleted_at IS NULL
         RETURNING *`,
                params
            );

            if (result.rows.length === 0) {
                throw new Error('Deal not found or unauthorized');
            }

            logger.info('Deal updated', { dealId, organizationId });
            return result.rows[0];
        } catch (error) {
            logger.error('Error updating deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * Update deal stage with validation
     * Phase 4 E-Sign: Triggers e-sign workflow if stage has trigger_esign = true
     */
    async updateDealStage(
        dealId: string,
        newStageId: string,
        organizationId: string,
        userId?: string,
        notes?: string
    ): Promise<Deal> {
        const client = await db.getClient();

        try {
            await client.query('BEGIN');

            // Get current deal
            const dealResult = await client.query<Deal>(
                `SELECT * FROM deals WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`,
                [dealId, organizationId]
            );

            if (dealResult.rows.length === 0) {
                throw new Error('Deal not found');
            }

            const deal = dealResult.rows[0];
            const oldStageId = deal.stage_id;

            // Validate stage transition
            await pipelineValidator.validateStageTransition(
                deal.pipeline_id,
                oldStageId,
                newStageId,
                organizationId
            );

            // Disable legacy triggers that reference non-existent columns
            await client.query('ALTER TABLE deals DISABLE TRIGGER trigger_deal_commission');
            await client.query('ALTER TABLE deals DISABLE TRIGGER trigger_update_agent_closing_rate');

            // Update deal stage
            const updateResult = await client.query<Deal>(
                `UPDATE deals
         SET stage_id = $1, stage_changed_at = NOW(), updated_at = NOW(), updated_by = $2
         WHERE id = $3 AND organization_id = $4
         RETURNING *`,
                [newStageId, userId || null, dealId, organizationId]
            );

            const updatedDeal = updateResult.rows[0];

            // Re-enable triggers
            await client.query('ALTER TABLE deals ENABLE TRIGGER trigger_deal_commission');
            await client.query('ALTER TABLE deals ENABLE TRIGGER trigger_update_agent_closing_rate');

            // Log stage change activity (also protected by savepoint)
            try {
                await client.query('SAVEPOINT activity_log');
                await activityService.createActivity(
                    {
                        deal_id: dealId,
                        user_id: userId || deal.assigned_agent,
                        activity_type: 'stage_change',
                        subject: 'Deal stage changed',
                        description: notes || 'Deal moved to new stage',
                        outcome: 'completed',
                        old_value: { stage_id: oldStageId },
                        new_value: { stage_id: newStageId },
                    },
                    client
                );
                await client.query('RELEASE SAVEPOINT activity_log');
            } catch (activityError: any) {
                await client.query('ROLLBACK TO SAVEPOINT activity_log');
                logger.warn('Failed to log stage change activity (legacy trigger)', {
                    dealId,
                    error: activityError.message,
                });
            }

            await client.query('COMMIT');

            logger.info('Deal stage updated', {
                dealId,
                organizationId,
                oldStageId,
                newStageId,
            });

            // ================================================================
            // Phase 4 E-Sign: Check if new stage triggers e-sign workflow
            // ================================================================
            try {
                await this.checkAndTriggerEsign(dealId, newStageId, organizationId, userId);
            } catch (esignError: any) {
                // Don't fail the stage update if e-sign fails, just log it
                logger.error('Failed to trigger e-sign for deal stage', {
                    dealId,
                    stageId: newStageId,
                    error: esignError.message,
                });
            }

            // ================================================================
            // Calendar: Log stage transition as a calendar event
            // ================================================================
            try {
                const stageRow = await db.query(
                    `SELECT stage_name FROM deal_stages WHERE id = $1`,
                    [newStageId]
                );
                const stageName = stageRow.rows[0]?.stage_name || 'Unknown Stage';

                const now = new Date();
                await calendarService.createEvent({
                    organizationId,
                    userId: userId || deal.assigned_agent || organizationId,
                    title: `Deal moved to ${stageName}: ${updatedDeal.title}`,
                    description: notes || `Deal "${updatedDeal.title}" transitioned to ${stageName}`,
                    eventType: 'milestone',
                    startTime: now,
                    endTime: new Date(now.getTime() + 30 * 60 * 1000), // 30 min
                    allDay: false,
                    dealId,
                    status: 'completed',
                });
            } catch (calError: any) {
                logger.error('Failed to create calendar event for deal stage transition', {
                    dealId,
                    stageId: newStageId,
                    error: calError.message,
                });
            }

            return updatedDeal;
        } catch (error) {
            await client.query('ROLLBACK');
            logger.error('Error updating deal stage', { error, dealId, organizationId });
            throw error;
        } finally {
            client.release();
        }
    }

    /**
     * Soft delete deal
     */
    async deleteDeal(dealId: string, organizationId: string): Promise<void> {
        try {
            const result = await db.query(
                `UPDATE deals
         SET deleted_at = NOW(), deal_status = 'archived'
         WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
         RETURNING id`,
                [dealId, organizationId]
            );

            if (result.rows.length === 0) {
                throw new Error('Deal not found or already deleted');
            }

            logger.info('Deal soft deleted', { dealId, organizationId });
        } catch (error) {
            logger.error('Error deleting deal', { error, dealId, organizationId });
            throw error;
        }
    }

    /**
     * Get deals by pipeline stage (for Kanban board)
     */
    async getDealsByStage(
        organizationId: string,
        pipelineId: string,
        agentId?: string
    ): Promise<Record<string, Deal[]>> {
        try {
            const params: any[] = [organizationId, pipelineId];
            let agentClause = '';
            if (agentId) {
                agentClause = ` AND d.assigned_agent = $3`;
                params.push(agentId);
            }
            const result = await db.query<Deal & { stage_name: string; stage_order: number }>(
                `SELECT 
          d.*,
          ds.stage_name,
          ds.stage_order,
          ds.stage_color,
          c.first_name || ' ' || c.last_name as primary_contact_name,
          (SELECT ARRAY_AGG(title) FROM crm_properties WHERE id = ANY(d.property_ids)) as property_names,
          (SELECT EXISTS(SELECT 1 FROM valuations v WHERE v.property_id = ANY(d.property_ids) AND v.status = 'completed')) as has_valuation
         FROM deals d
         JOIN deal_stages ds ON d.stage_id = ds.id
         LEFT JOIN contacts c ON d.primary_contact_id = c.id
         WHERE d.organization_id = $1 
           AND d.pipeline_id = $2 
           AND d.deleted_at IS NULL
           AND d.deal_status = 'active'${agentClause}
         ORDER BY ds.stage_order, d.created_at DESC`,
                params
            );

            // Group by stage
            const dealsByStage: Record<string, Deal[]> = {};
            for (const deal of result.rows) {
                const stageId = deal.stage_id;
                if (!dealsByStage[stageId]) {
                    dealsByStage[stageId] = [];
                }
                dealsByStage[stageId].push(deal);
            }

            return dealsByStage;
        } catch (error) {
            logger.error('Error fetching deals by stage', { error, organizationId, pipelineId });
            throw error;
        }
    }

    /**
     * Get deal metrics
     */
    async getDealMetrics(organizationId: string): Promise<{
        total_active: number;
        total_value: number;
        total_weighted_value: number;
        won_deals: number;
        lost_deals: number;
        avg_close_probability: number;
        by_stage: Record<string, { count: number; total_value: number }>;
    }> {
        try {
            const result = await db.query(
                `SELECT 
          COUNT(*) FILTER (WHERE deal_status = 'active') as total_active,
          COUNT(*) FILTER (WHERE deal_status = 'won') as won_deals,
          COUNT(*) FILTER (WHERE deal_status = 'lost') as lost_deals,
          COALESCE(SUM(deal_value) FILTER (WHERE deal_status = 'active'), 0) as total_value,
          COALESCE(SUM(weighted_value) FILTER (WHERE deal_status = 'active'), 0) as total_weighted_value,
          AVG(close_probability) FILTER (WHERE deal_status = 'active') as avg_close_probability
         FROM deals
         WHERE organization_id = $1 AND deleted_at IS NULL`,
                [organizationId]
            );

            const metrics = result.rows[0];

            // Get by stage
            const stageResult = await db.query(
                `SELECT 
          ds.stage_name,
          COUNT(d.id) as count,
          COALESCE(SUM(d.deal_value), 0) as total_value
         FROM deal_stages ds
         LEFT JOIN deals d ON ds.id = d.stage_id AND d.deal_status = 'active' AND d.deleted_at IS NULL
         JOIN deal_pipelines dp ON ds.pipeline_id = dp.id
         WHERE dp.organization_id = $1
         GROUP BY ds.stage_name`,
                [organizationId]
            );

            const byStage: Record<string, { count: number; total_value: number }> = {};
            for (const row of stageResult.rows) {
                byStage[row.stage_name] = {
                    count: parseInt(row.count, 10),
                    total_value: parseFloat(row.total_value),
                };
            }

            return {
                total_active: parseInt(metrics.total_active, 10),
                total_value: parseFloat(metrics.total_value),
                total_weighted_value: parseFloat(metrics.total_weighted_value),
                won_deals: parseInt(metrics.won_deals, 10),
                lost_deals: parseInt(metrics.lost_deals, 10),
                avg_close_probability: parseFloat(metrics.avg_close_probability) || 50,
                by_stage: byStage,
            };
        } catch (error) {
            logger.error('Error fetching deal metrics', { error, organizationId });
            throw error;
        }
    }

    // ================================================================
    // E-SIGN INTEGRATION (Phase 4)
    // ================================================================

    /**
     * Check if stage triggers e-sign and initiate workflow if so
     */
    private async checkAndTriggerEsign(
        dealId: string,
        stageId: string,
        organizationId: string,
        userId?: string
    ): Promise<void> {
        // Get stage configuration
        const stageResult = await db.query(
            `SELECT 
                trigger_esign, 
                esign_template_id,
                esign_document_subject,
                esign_document_message,
                signer_config,
                field_placements,
                auto_advance_on_sign,
                next_stage_on_sign,
                stage_name
             FROM deal_stages 
             WHERE id = $1`,
            [stageId]
        );

        if (stageResult.rows.length === 0) {
            return;
        }

        const stage = stageResult.rows[0];

        // Check if this stage triggers e-sign
        if (!stage.trigger_esign) {
            return;
        }

        logger.info('Stage triggers e-sign workflow', {
            dealId,
            stageId,
            stageName: stage.stage_name,
        });

        // Trigger e-sign workflow
        await this.triggerDealEsign(
            dealId,
            organizationId,
            {
                templateId: stage.esign_template_id,
                subject: stage.esign_document_subject,
                message: stage.esign_document_message,
                signerConfig: stage.signer_config || [],
                fieldPlacements: stage.field_placements || [],
                autoAdvanceOnSign: stage.auto_advance_on_sign,
                nextStageOnSign: stage.next_stage_on_sign,
            },
            userId
        );
    }

    /**
     * Trigger e-sign workflow for a deal
     */
    async triggerDealEsign(
        dealId: string,
        organizationId: string,
        config: {
            templateId?: string;
            subject?: string;
            message?: string;
            signerConfig: any[];
            fieldPlacements: any[];
            autoAdvanceOnSign?: boolean;
            nextStageOnSign?: string;
        },
        userId?: string
    ): Promise<{ envelopeId: string } | null> {
        try {
            // Get deal with full details
            const deal = await this.getDealById(dealId, organizationId);
            if (!deal) {
                throw new Error(`Deal not found: ${dealId}`);
            }

            // Generate or get document
            let documentBuffer: Buffer;
            let documentName: string;

            if (config.templateId) {
                // Generate document from template
                const { documentGenerationService } = await import('./documentGenerationService');
                const generatedDoc = await documentGenerationService.generate(
                    organizationId,
                    { templateId: config.templateId, dealId },
                    userId || deal.assigned_agent
                );
                documentBuffer = await this.fetchDocumentFromUrl(generatedDoc.file_url);
                documentName = generatedDoc.file_name;
            } else {
                // Look for existing document to sign
                const docResult = await db.query(
                    `SELECT * FROM crm_generated_documents 
                     WHERE deal_id = $1 AND organization_id = $2 AND is_signed = false
                     ORDER BY created_at DESC LIMIT 1`,
                    [dealId, organizationId]
                );

                if (docResult.rows.length === 0) {
                    throw new Error('No document available for signing');
                }

                const doc = docResult.rows[0];
                documentBuffer = await this.fetchDocumentFromUrl(doc.file_url);
                documentName = doc.document_name;
            }

            // Resolve signers from config
            const signers = await this.resolveSigners(deal, config.signerConfig, organizationId);

            if (signers.length === 0) {
                throw new Error('No valid signers could be resolved for this deal');
            }

            // Build signature fields
            const fields = this.buildSignatureFields(signers, config.fieldPlacements);

            // Create envelope
            const envelope = await eSignIntegrationService.createEnvelope({
                subject: config.subject || `Contract - ${deal.title}`,
                message: config.message || `Please review and sign the contract for ${deal.title}.`,
                documents: [{
                    name: documentName,
                    content: documentBuffer,
                    mimeType: 'application/pdf',
                    source: 'system_generated',
                }],
                signers: signers.map((s, idx) => ({
                    name: s.name,
                    email: s.email,
                    role: 'signer',
                    order: s.order || idx + 1,
                })),
                fields,
                sourceModule: 'crm',
                sourceEntityType: 'deal',
                sourceEntityId: dealId,
                expiresInDays: 30,
            });

            // Update deal with envelope reference
            await db.query(
                `UPDATE deals 
                 SET current_esign_envelope_id = $1,
                     esign_status = 'pending',
                     esign_triggered_at = NOW(),
                     updated_at = NOW()
                 WHERE id = $2`,
                [envelope.envelopeId, dealId]
            );

            // Store auto-advance config if set
            if (config.autoAdvanceOnSign && config.nextStageOnSign) {
                await db.query(
                    `UPDATE deals 
                     SET custom_fields = COALESCE(custom_fields, '{}'::jsonb) || $1
                     WHERE id = $2`,
                    [
                        JSON.stringify({
                            esign_auto_advance: true,
                            esign_next_stage: config.nextStageOnSign,
                        }),
                        dealId,
                    ]
                );
            }

            // Log audit event
            await this.logCrmEsignAudit(dealId, envelope.envelopeId, 'esign_triggered', {
                signers: signers.map(s => ({ email: s.email, name: s.name, role: s.role })),
                documentName,
                subject: config.subject,
            }, userId);

            // Log activity
            await activityService.createActivity({
                deal_id: dealId,
                user_id: userId || deal.assigned_agent,
                activity_type: 'document_request',
                subject: 'Contract sent for e-signature',
                description: `Contract "${documentName}" sent to ${signers.map(s => s.name).join(', ')} for signing`,
                new_value: {
                    envelope_id: envelope.envelopeId,
                    signers: signers.map(s => ({ email: s.email, name: s.name })),
                },
            });

            logger.info('E-sign envelope created for deal', {
                dealId,
                envelopeId: envelope.envelopeId,
                signerCount: signers.length,
            });

            return { envelopeId: envelope.envelopeId };
        } catch (error: any) {
            logger.error('Failed to trigger e-sign for deal', {
                dealId,
                error: error.message,
            });
            throw error;
        }
    }

    /**
     * Handle e-sign completion webhook for CRM deals
     */
    async handleEsignCompletion(event: CompletionEvent): Promise<void> {
        const { envelope, sourceContext, documents, signers } = event;

        if (sourceContext.entityType !== 'deal') {
            logger.warn('Invalid entity type for CRM e-sign completion', {
                expected: 'deal',
                received: sourceContext.entityType,
            });
            return;
        }

        const dealId = sourceContext.entityId;

        try {
            // Get deal with custom fields
            const dealResult = await db.query(
                `SELECT * FROM deals WHERE id = $1`,
                [dealId]
            );

            if (dealResult.rows.length === 0) {
                throw new Error(`Deal not found: ${dealId}`);
            }

            const deal = dealResult.rows[0];
            const customFields = deal.custom_fields || {};
            const signedDoc = documents?.[0];

            // Update deal with completion info
            await db.query(
                `UPDATE deals 
                 SET esign_status = 'completed',
                     esign_completed_at = NOW(),
                     signed_contract_url = $1,
                     esign_certificate_url = $2,
                     updated_at = NOW()
                 WHERE id = $3`,
                [
                    signedDoc?.signedUrl || null,
                    signedDoc?.certificateUrl || null,
                    dealId,
                ]
            );

            // Log audit event for each signer
            for (const signer of signers || []) {
                await this.logCrmEsignAudit(dealId, envelope.id, 'signer_signed', {
                    signerEmail: signer.email,
                    signerName: signer.name,
                    signedAt: signer.signedAt,
                    pmtId: signer.pmtId,
                }, undefined, signer.email, signer.name, signer.ipAddress);
            }

            // Log completion audit event
            await this.logCrmEsignAudit(dealId, envelope.id, 'completed', {
                completedAt: envelope.completedAt,
                signedDocumentUrl: signedDoc?.signedUrl,
                certificateUrl: signedDoc?.certificateUrl,
            });

            // Log activity
            await activityService.createActivity({
                deal_id: dealId,
                user_id: deal.assigned_agent,
                activity_type: 'document_received',
                subject: 'Contract fully signed',
                description: `All parties have signed the contract`,
                new_value: {
                    envelope_id: envelope.id,
                    signed_url: signedDoc?.signedUrl,
                    signers: signers?.map(s => ({ name: s.name, email: s.email, signedAt: s.signedAt })),
                },
            });

            // Auto-advance stage if configured
            if (customFields.esign_auto_advance && customFields.esign_next_stage) {
                try {
                    await this.updateDealStage(
                        dealId,
                        customFields.esign_next_stage,
                        deal.organization_id,
                        undefined,
                        'Auto-advanced after contract signing'
                    );

                    await this.logCrmEsignAudit(dealId, envelope.id, 'auto_advanced', {
                        newStageId: customFields.esign_next_stage,
                    });

                    logger.info('Deal auto-advanced after e-sign completion', {
                        dealId,
                        newStageId: customFields.esign_next_stage,
                    });
                } catch (advanceError: any) {
                    logger.error('Failed to auto-advance deal stage', {
                        dealId,
                        error: advanceError.message,
                    });
                }
            }

            logger.info('CRM deal e-sign completion processed', {
                dealId,
                envelopeId: envelope.id,
            });
        } catch (error: any) {
            logger.error('Failed to process CRM deal e-sign completion', {
                dealId,
                envelopeId: envelope.id,
                error: error.message,
            });
            throw error;
        }
    }

    /**
     * Resolve signers from signer configuration
     */
    private async resolveSigners(
        deal: Deal & { primary_contact_name?: string; primary_contact_email?: string },
        signerConfig: any[],
        organizationId: string
    ): Promise<Array<{ name: string; email: string; role: string; order: number }>> {
        const signers: Array<{ name: string; email: string; role: string; order: number }> = [];

        // Import contactService dynamically to avoid circular deps
        const { contactService } = await import('./contactService');

        for (const config of signerConfig) {
            try {
                let name = '';
                let email = '';

                switch (config.source || config.data_source) {
                    case 'primary_contact':
                        if (deal.primary_contact_id) {
                            const contact = await contactService.getContactById(
                                deal.primary_contact_id,
                                organizationId
                            );
                            if (contact) {
                                name = `${contact.first_name} ${contact.last_name}`;
                                email = contact.email || '';
                            }
                        }
                        break;

                    case 'secondary_contact':
                        if (deal.secondary_contacts && deal.secondary_contacts.length > 0) {
                            const contactId = deal.secondary_contacts[0];
                            const contact = await contactService.getContactById(contactId, organizationId);
                            if (contact) {
                                name = `${contact.first_name} ${contact.last_name}`;
                                email = contact.email || '';
                            }
                        }
                        break;

                    case 'assigned_agent':
                        if (deal.assigned_agent) {
                            const agentResult = await db.query(
                                `SELECT first_name, last_name, email 
                                 FROM agents WHERE id = $1`,
                                [deal.assigned_agent]
                            );
                            if (agentResult.rows.length > 0) {
                                const agent = agentResult.rows[0];
                                name = `${agent.first_name} ${agent.last_name}`;
                                email = agent.email || '';
                            }
                        }
                        break;

                    case 'property_owner':
                        if (deal.property_ids && deal.property_ids.length > 0) {
                            const propResult = await db.query(
                                `SELECT owner_name, owner_email 
                                 FROM crm_properties WHERE id = $1`,
                                [deal.property_ids[0]]
                            );
                            if (propResult.rows.length > 0) {
                                const prop = propResult.rows[0];
                                name = prop.owner_name || '';
                                email = prop.owner_email || '';
                            }
                        }
                        break;

                    case 'company_contact':
                        if (deal.company_id) {
                            const compResult = await db.query(
                                `SELECT c.first_name, c.last_name, c.email
                                 FROM companies comp
                                 JOIN contacts c ON comp.primary_contact_id = c.id
                                 WHERE comp.id = $1`,
                                [deal.company_id]
                            );
                            if (compResult.rows.length > 0) {
                                const contact = compResult.rows[0];
                                name = `${contact.first_name} ${contact.last_name}`;
                                email = contact.email || '';
                            }
                        }
                        break;

                    case 'manual':
                        // Manual signers should have name and email in config
                        name = config.name || '';
                        email = config.email || '';
                        break;
                }

                // Only add if we have valid name and email
                if (name && email) {
                    signers.push({
                        name,
                        email,
                        role: config.role || 'signer',
                        order: config.order || signers.length + 1,
                    });
                } else {
                    logger.warn('Could not resolve signer', {
                        config,
                        dealId: deal.id,
                    });
                }
            } catch (resolveError: any) {
                logger.error('Error resolving signer', {
                    config,
                    error: resolveError.message,
                });
            }
        }

        return signers;
    }

    /**
     * Build signature fields from placements config
     */
    private buildSignatureFields(
        signers: Array<{ email: string; role: string }>,
        fieldPlacements: any[]
    ): ESignField[] {
        const fields: ESignField[] = [];

        for (const placement of fieldPlacements) {
            // Find the signer for this field placement
            const signer = signers.find(s => s.role === placement.role) || signers[0];
            if (!signer) continue;

            fields.push({
                type: placement.type || 'signature',
                recipientEmail: signer.email,
                documentIndex: placement.documentIndex || 0,
                page: placement.page || 1,
                x: placement.x || 0.10,
                y: placement.y || 0.70,
                width: placement.width || 0.30,
                height: placement.height || 0.10,
                required: placement.required ?? true,
                label: placement.label,
            });
        }

        // If no field placements configured, add default signature fields for each signer
        if (fields.length === 0) {
            signers.forEach((signer, idx) => {
                fields.push({
                    type: 'signature',
                    recipientEmail: signer.email,
                    documentIndex: 0,
                    page: 1,
                    x: 0.10,
                    y: 0.70 - (idx * 0.15), // Stack signatures vertically
                    width: 0.30,
                    height: 0.10,
                    required: true,
                });
            });
        }

        return fields;
    }

    /**
     * Fetch document from URL
     */
    private async fetchDocumentFromUrl(url: string): Promise<Buffer> {
        try {
            // If it's a storage key, use document service
            if (!url.startsWith('http')) {
                const { documentService } = await import('../../../shared-services/document-service');
                const { buffer } = await documentService.storage.download(url);
                return buffer;
            }

            // Otherwise fetch from URL
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`Failed to fetch document: ${response.statusText}`);
            }
            const arrayBuffer = await response.arrayBuffer();
            return Buffer.from(arrayBuffer);
        } catch (error: any) {
            logger.error('Failed to fetch document', { url, error: error.message });
            throw error;
        }
    }

    /**
     * Log e-sign audit event for CRM
     */
    private async logCrmEsignAudit(
        dealId: string,
        envelopeId: string | null,
        eventType: string,
        eventData: Record<string, any>,
        userId?: string,
        signerEmail?: string,
        signerName?: string,
        signerIp?: string
    ): Promise<void> {
        await db.query(
            `INSERT INTO crm_esign_audit (
                id, deal_id, envelope_id, event_type, event_data,
                signer_email, signer_name, signer_ip_address, created_by
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
            [
                uuidv4(),
                dealId,
                envelopeId,
                eventType,
                JSON.stringify(eventData),
                signerEmail || null,
                signerName || null,
                signerIp || null,
                userId || null,
            ]
        );
    }
}

export const dealService = new DealService();
